<a href="https://colab.research.google.com/github/suhani242/T170800236_TNS_AIML/blob/main/AIML_day4_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1, 2, 3], [4, 5, 6],[9,10,11],[11,12,13]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

zeros = np.zeros((5,3))
ones = np.ones((2,3))
identity = np.eye(6)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)

arange_arr = np.arange(1, 46, 5)
linspace_arr = np.linspace(1, 10, 10)

print("Arange:", arange_arr)
print("Linspace:", linspace_arr)

rand_arr = np.random.rand(4,5)
print("Random Array:\n", rand_arr)
otp =( (rand_arr*1000000)).astype(int)
print("Random Array:\n", otp)

1D Array: [1 2 3 4 5 6]
2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]
 [11 12 13]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Arange: [ 1  6 11 16 21 26 31 36 41]
Linspace: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Random Array:
 [[0.11124283 0.05057747 0.40233938 0.64682598 0.98966386]
 [0.60784766 0.70781954 0.57354092 0.46821883 0.34439159]
 [0.29356377 0.66043131 0.97899275 0.43856312 0.14527639]
 [0.08394557 0.1448214  0.42205304 0.77630966 0.50648017]]
Random Array:
 [[111242  50577 402339 646825 989663]
 [607847 707819 573540 468218 344391]
 [293563 660431 978992 438563 145276]
 [ 83945 144821 422053 776309 506480]]


In [2]:
matrix = np.arange(1, 13).reshape(4,3)
print("Matrix:\n", matrix)
print("Transpose:\n", matrix.T)

arr = np.array([10, 20, 30, 40])
print("Original Array:", arr)
print("Array + 5:", arr + 5)
print("Array squared:", arr ** 2)

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n", np.dot(A,B))

unsorted = np.array([3,1,4,1,5,9])
print("Sorted Array:", np.sort(unsorted))

Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Original Array: [10 20 30 40]
Array + 5: [15 25 35 45]
Array squared: [ 100  400  900 1600]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949
Matrix Multiplication:
 [[19 22]
 [43 50]]
Sorted Array: [1 1 3 4 5 9]


In [3]:
#Pandas

from typing_extensions import dataclass_transform

import pandas as pd

data = [10, 20,30,40, 40]
print(data)
series = pd.Series(data, index=[1001,1002,1003,'disha','bharti'])
print("Series:\n", series)

# Creating a DataFrame
data_dict = {
    'Name': ['Alice', 'suhani','jiya', 'Charlie', 'David','Kartik','Kartik','Harshali','Yuvraj'],
    'Age': [24,34, 25, 22,4,17,15,20,20],
    'City': ['New York', 'New Delhi','New Jersey', 'London', 'Tokyo','Mumbai','Chicago','Washington','Washington']

}
print(data_dict)
df = pd.DataFrame(data_dict)
print("\nDataFrame:\n", df)

print("\nHead:\n", df.head())
print("\nInfo:\n")
print(df.info())
print("\nDescribe:\n", df.describe())

[10, 20, 30, 40, 40]
Series:
 1001      10
1002      20
1003      30
disha     40
bharti    40
dtype: int64
{'Name': ['Alice', 'suhani', 'jiya', 'Charlie', 'David', 'Kartik', 'Kartik', 'Harshali', 'Yuvraj'], 'Age': [24, 34, 25, 22, 4, 17, 15, 20, 20], 'City': ['New York', 'New Delhi', 'New Jersey', 'London', 'Tokyo', 'Mumbai', 'Chicago', 'Washington', 'Washington']}

DataFrame:
        Name  Age        City
0     Alice   24    New York
1    suhani   34   New Delhi
2      jiya   25  New Jersey
3   Charlie   22      London
4     David    4       Tokyo
5    Kartik   17      Mumbai
6    Kartik   15     Chicago
7  Harshali   20  Washington
8    Yuvraj   20  Washington

Head:
       Name  Age        City
0    Alice   24    New York
1   suhani   34   New Delhi
2     jiya   25  New Jersey
3  Charlie   22      London
4    David    4       Tokyo

Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ---

In [4]:
print("Single Column:\n", df['Name'])
print("\nMultiple Columns:\n", df[['Name', 'Age']])
print("\nRow by index (iloc):\n", df.iloc[1])
print("\nRow by label (loc):\n", df.loc[1])

print("\nPeople older than 18:\n", df[df['Age'] > 18])
df['Salary'] = [50000, 60000, 55000, 70000,45000,90000,100000,10000,20000]
print("\nWith Salary Column:\n", df)

df2 = pd.DataFrame({
    'A': [1, 2, None, 4],
    'B': [5, None, None, 8]
})
print("\nOriginal with NaN:\n", df2)
print("\nDrop NaN:\n", df2.dropna())
print("\nFill NaN with 0:\n", df2.fillna(2.0))

grouped = df.groupby('City')['Salary'].mean()
print("\nAverage Salary by City:\n", grouped)

print("\nSorted by Age:\n", df.sort_values(by='Age'))


df_extra = pd.DataFrame({
    'Name': ['Suhani', 'Rahul'],
    'Department': ['HR', 'IT']
})
merged = pd.merge(df, df_extra, on='Name', how='outer')
print("\nMerged DataFrame:\n", merged)


Single Column:
 0       Alice
1      suhani
2        jiya
3     Charlie
4       David
5      Kartik
6      Kartik
7    Harshali
8      Yuvraj
Name: Name, dtype: object

Multiple Columns:
        Name  Age
0     Alice   24
1    suhani   34
2      jiya   25
3   Charlie   22
4     David    4
5    Kartik   17
6    Kartik   15
7  Harshali   20
8    Yuvraj   20

Row by index (iloc):
 Name       suhani
Age            34
City    New Delhi
Name: 1, dtype: object

Row by label (loc):
 Name       suhani
Age            34
City    New Delhi
Name: 1, dtype: object

People older than 18:
        Name  Age        City
0     Alice   24    New York
1    suhani   34   New Delhi
2      jiya   25  New Jersey
3   Charlie   22      London
7  Harshali   20  Washington
8    Yuvraj   20  Washington

With Salary Column:
        Name  Age        City  Salary
0     Alice   24    New York   50000
1    suhani   34   New Delhi   60000
2      jiya   25  New Jersey   55000
3   Charlie   22      London   70000
4     Dav